@startuml
skinparam classAttributeIconSize 0
class DriverCli{
+ DriverCli()
+ {static} listDrivers() : void
+ startFlow() : void
+ toString() : String
+ {static} initiateClass() : void
+ {static} newInstance(line : String) : void
}
DriverCli --|> UserCli
class Driver{
+ {static} instances : ArrayList<Savable>
+ {static} className : String
+ {static} savedPath : String
+ Driver(name : String, username : String, password : String, Email : String)
+ Driver(id : int, name : String, username : String, password : String, Email : String)
+ {static} _listDrivers() : String
+ {static} listDrivers() : void
+ toString() : String
+ {static} initiateClass() : void
+ {static} newInstance(line : String) : void
}
Driver --|> User
class Login{
- usernameField : TextField
- passwordField : JTextField
- className : String
+ Login(text : String)
- signIn() : void
}
Login --|> Frame
class DriverGui{
- personalInfoButton : Button
- outputArea : TextArea
+ DriverGui(Driver : User)
- personalInfo() : void
- listAssignedTrips() : void
}
DriverGui --|> UserGui
class Register{
- usernameField : TextField
- passwordField : JTextField
- className : String
+ Register(text : String)
- signUp() : void
}
Register --|> Frame
class Ticket{
+ {static} instances : ArrayList<Savable>
+ {static} csvHeader : String
+ {static} savedPath : String
+ {static} className : String
+ passengerId : int
+ tripId : int
+ Ticket(passengerId : int, tripId : int)
+ Ticket(id : int, passengerId : int, tripId : int)
+ toCsv() : String
+ {static} _listTickets(passengerId : int) : String
+ {static} listTickets(passengerId : int) : void
+ toString() : String
+ {static} newInstance(line : String) : void
+ {static} removeTicket(id : int) : void
+ {static} initiateClass() : void
}
Ticket --|> Savable
class MainFrame{
+ MainFrame()
}
MainFrame --|> Frame
class ManagerCli{
+ ManagerCli()
+ startFlow() : void
+ addEmployee(scanner : Scanner) : void
+ addVehicle(scanner : Scanner) : void
+ addTrip(scanner : Scanner) : void
+ removeTrip(scanner : Scanner) : void
+ editTrip(scanner : Scanner, driver : boolean) : void
+ {static} initiateClass() : void
+ {static} newInstance(line : String) : void
}
ManagerCli --|> UserCli
class Data{
+ {static} main() : void
+ {static} getDialog(message : String, type : String) : String
}
class PassengersGUI{
- selectTripButton : JButton
- outputTextArea : JTextArea
+ PassengersGUI()
- selectTrip() : void
- reviewTicket() : void
- cancelTicket() : void
- viewInfo() : void
+ {static} main(args : String[]) : void
}
PassengersGUI --|> JFrame
class PassengerCli{
+ PassengerCli()
+ startFlow() : void
- removeTicket(scanner : Scanner) : void
- bookATicket(scanner : Scanner) : void
}
PassengerCli --|> UserCli
class P1{
+ P1()
}
P1 --|> Font
class PassengerGui{
- BookATicketButton : Button
- outputArea : TextArea
+ PassengerGui(passenger : User)
- bookATicket() : void
- listTickets() : void
- removeTicket() : void
}
PassengerGui --|> UserGui
class Manager{
+ {static} instances : ArrayList<Savable>
+ {static} className : String
+ {static} savedPath : String
+ Manager(id : int, name : String, username : String, password : String, Email : String)
+ {static} initiateClass() : void
+ {static} newInstance(line : String) : void
}
Manager --|> User
class UserGui{
+ user : User
+ UserGui(title : String, theUser : User)
}
UserGui --|> Frame
class UserCli{
+ {static} csvHeader : String
+ id : int
+ name : String
+ username : String
+ password : String
+ Email : String
+ success : boolean
+ UserCli(instances : ArrayList<Savable>, savedPath : String, className : String)
+ register(instances : ArrayList<Savable>, savedPath : String, className : String) : void
+ toCsv() : String
+ login(instances : ArrayList<Savable>) : boolean
+ {static} initiateClass(usersFile : String, className : String, instances : ArrayList<Savable>) : void
}
class Frame{
+ Frame(title : String)
+ Frame()
+ start() : void
}
Frame --|> JFrame
class TextArea{
+ TextArea()
}
TextArea --|> JTextArea
class Button{
+ Button(text : String)
}
Button --|> JButton
class ManagerGui{
- ListTripsButton : Button
- outputArea : TextArea
+ ManagerGui(Manager : User)
- listTrips() : void
- addTrip() : void
- removeTrip() : void
- editTrip() : void
- assignDriver() : void
- addVehicle() : void
- addEmployee() : void
}
ManagerGui --|> UserGui
class Trip{
+ {static} instances : ArrayList<Savable>
+ {static} csvHeader : String
+ {static} savedPath : String
+ {static} className : String
+ type : String
+ source : String
+ destination : String
+ cycle : String
+ stops : int
+ seats : int
+ price : int
+ driverId : int
+ Trip(type : String, source : String, destination : String, stops : int, seats : int, price : int, driverId : int, cycle : String)
+ Trip(id : int, type : String, source : String, destination : String, stops : int, seats : int, price : int, driverId : int, cycle : String)
+ {static} initiateClass() : void
+ {static} newInstance(line : String) : void
+ toCsv() : String
+ allInfo() : String
+ assignDriver() : void
+ editTrip() : void
+ info() : String
+ toString() : String
+ toString(info : String) : String
}
Trip --|> Savable
class User{
+ {static} csvHeader : String
+ name : String
+ username : String
+ password : String
+ Email : String
+ success : boolean
+ User()
+ User(id : int, name : String, username : String, password : String, Email : String)
+ User(name : String, username : String, password : String, Email : String, instances : ArrayList<Savable>)
+ {static} login(username : String, password : String, instances : ArrayList<Savable>) : User
+ {static} register(name : String, Email : String, username : String, password : String, instances : ArrayList<Savable>, savedPath : String, className : String) : User
+ toCsv() : String
+ {static} initiateClass(usersFile : String, className : String, instances : ArrayList<Savable>) : void
}
User --|> Savable
class Dialog{
+ Dialog(parent : JFrame, title : String)
}
Dialog --|> JDialog
class MainFlow{
+ MainFlow()
}
class Savable{
+ {static} nTrip : String
+ {static} nTicket : String
+ {static} nVehicle : String
+ {static} nPassenger : String
+ {static} nManager : String
+ {static} nDriver : String
+ index : int
+ id : int
+ Savable()
+ {static} generateId(instances : ArrayList<Savable>) : int
+ toCsv() : String
+ toString() : String
+ writeInstance(savedPath : String) : void
+ {static} removeInstance(id : int, instances : ArrayList<Savable>, savedPath : String, csvHeader : String) : void
+ {static} getById(id : int, instances : ArrayList<Savable>) : Savable
+ {static} removeInstance(id : int, className : String, instances : ArrayList<Savable>, savedPath : String, csvHeader : String) : void
+ {static} initiateClass(savedPath : String, csvHeader : String, className : String, instances : ArrayList<Savable>) : void
+ {static} saveInstances(instances : ArrayList<Savable>, savedPath : String, csvHeader : String) : void
- {static} newInstance(line : String, className : String) : void
+ {static} getSaved(instances : ArrayList<Savable>, savedPath : String, className : String, csvHeader : String) : void
+ {static} _listInstances(instances : ArrayList<Savable>) : String
+ {static} listInstances(instances : ArrayList<Savable>) : void
+ {static} writeToFile(fileName : String, data : String) : boolean
+ {static} _writeToFile(fileName : String, data : String, append : boolean) : boolean
+ {static} _getData(scanner : Scanner, prompt : String, type : String) : String
+ {static} getData(scanner : Scanner, prompt : String) : String
}
class P2{
+ P2()
}
P2 --|> Font
class Validations{
+ {static} valid(text : String, type : String) : boolean
- {static} validTripType(text : String) : boolean
- {static} validCycle(text : String) : boolean
- {static} validEmail(email : String) : boolean
- {static} validPass(pass : String) : boolean
- {static} validUsername(username : String, instances : ArrayList<Savable>) : boolean
- {static} validName(text : String) : boolean
- {static} validString(text : String) : boolean
- {static} validInt(text : String) : boolean
}
class Label{
+ Label(text : String)
}
Label --|> JLabel
class Passenger{
+ {static} instances : ArrayList<Savable>
+ {static} savedPath : String
+ {static} className : String
+ Passenger(id : int, name : String, username : String, password : String, Email : String)
+ {static} initiateClass() : void
+ {static} newInstance(line : String) : void
}
Passenger --|> User
class TextField{
+ TextField()
}
TextField --|> JTextField
class Vehicle{
+ {static} instances : ArrayList<Savable>
+ {static} csvHeader : String
+ {static} savedPath : String
- type : String
- capacity : int
- licensePlate : String
+ Vehicle(type : String, capacity : int, licensePlate : String)
+ setType(type : String) : void
+ {static} newInstance(line : String) : void
+ setCapacity(capacity : int) : void
+ toString() : String
+ displayInfo() : void
+ toCsv() : String
+ {static} initiateClass() : void
}
Vehicle --|> Savable
class Main{
+ {static} main(args : String[]) : void
- {static} gui() : void
- {static} cli() : void
}
Login--"- usernameField" TextField
DriverGui--"- personalInfoButton" Button
DriverGui--"- outputArea" TextArea
Register--"- usernameField" TextField
PassengerGui--"- BookATicketButton" Button
PassengerGui--"- outputArea" TextArea
UserGui--"+ user" User
ManagerGui--"- ListTripsButton" Button
ManagerGui--"- outputArea" TextArea
@enduml